DO NOT MERGE - added sparkswap to ccxt
sparkswap/ccxt pull request #1
Opened 2018-09-28 20:21 UTC by dannypaz

This is an example PR so that we can view the changes to this branch. All edits to CCXT should be made against the `adding-sparkswap` branch.

The only file we need to add is `sparkswap.js`. The CCXT build command will auto generate all documentation and php/python files which are not required to be checked in to the library initially.

In order to build the branch you need to install `tox` and `pandoc`. Make sure you have python 3 and PHP installed as well.

```
brew update
brew install python php pandoc tox
```

2018-10-02 19:52 UTC, martineehrlich requested changes

2018-10-02 19:52 UTC, martineehrlich commented on js/sparkswap.js
> +                        'v1/markets_stats', // get market stats for a specific market
v1/market_stats

2018-10-02 20:14 UTC, martineehrlich approved these changes
LGTM

2018-10-09 19:48 UTC, martineehrlich commented on js/sparkswap.js
> +                'deposit': 'emulated',
We did not implement this. Were we supposed to?

2018-11-01 17:07 UTC, dannypaz commented
@martineehrlich @treygriffith closing this PR but _not_ deleting the branch. The code in ccxt has been heavily modified and no longer fully represents the changes. https://github.com/ccxt/ccxt/pull/3974

2018-11-01 17:07 UTC, closed without merging